/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_GAMECIRCLE_H
#define S3E_EXT_GAMECIRCLE_H

#include "s3eTypes.h"

/**
 * @addtogroup s3egroup
 * @{
 */

/**
 * @defgroup gamecircleapigroup S3E Amazon Billing API reference
 *
 * Provides an API for Amazon Game Circle.
 *
 * @supported
 * - android
 *
 * @platnote This API is for Android only. 
 *
 */

/**
 * @}
 * @addtogroup gamecircleapigroup
 * @{
 */


/**
 * Indicates the maximum number of SKUs that can be provided to s3eAmazonInitiatePurchaseUpdatesRequest()
 */
//#define s3eAmazonBilling_ITEM_DATA_REQUEST_MAX_SKUS 100


/**
 * s3eGameCircleGamesFeature type
 * Enumeration of features Amazon Games provides. Used when initializing the AmazonGamesClient to list the features used by the application.
 */
typedef enum s3eGameCircleGamesFeature {
    /**
     * The achievement service is used.
     */
    S3E_GAMECIRCLE_ACHIEVEMENTS = 0,
    /**
     *  The leaderboard service is used.
     */
    S3E_GAMECIRCLE_LEADERBOARDS = 1,
    /**
     *  The whispersync service is used.
     */
    S3E_GAMECIRCLE_WHISPERSYNC = 2
} s3eGameCircleGamesFeature;


/**
 * s3eGameCircleStatus type
 * Status values that are only of interest to the client (i.e. not to be used by the service)
 */
typedef enum s3eGameCircleStatus {
    /**
     * The service could not authorize the client.
     */
    S3E_GAMECIRCLE_CANNOT_AUTHORIZE = 5,
    /**
     * The service could not bind either because it does not exist, or permissions have not been granted.
     */
    S3E_GAMECIRCLE_CANNOT_BIND = 3,
    /**
     * The service is in the process of initializing.
     */
    S3E_GAMECIRCLE_INITIALIZING = 0,
    /**
     * The current session is not longer valid.
     */
    S3E_GAMECIRCLE_INVALID_SESSION = 4,
    /**
     * The device is not registered with an account
     */
    S3E_GAMECIRCLE_NOT_AUTHENTICATED = 8,
    /**
     * The game in not authorized to use the service.
     */
    S3E_GAMECIRCLE_NOT_AUTHORIZED = 6,
    /**
     * The service is connected and ready to be used
     */
    S3E_GAMECIRCLE_SERVICE_CONNECTED = 1,
    /**
     * The service has been disconnected, most likely forcefully by the operating system
     */
    S3E_GAMECIRCLE_SERVICE_DISCONNECTED = 2,
    /**
     * The device is not opted-in to use the service
     */
    S3E_GAMECIRCLE_SERVICE_NOT_OPTED_IN = 7,
    /**
     * Initialize callback not still returned.
     */
    S3E_GAMECIRCLE_STILL_INITIALIZING = 9,
    /**
     * Initialize method was not called
     */
    S3E_GAMECIRCLE_STILL_INIT_NOT_CALLED = 10
} s3eGameCircleStatus;


/**
 * LeaderboardFilter type
 * 
 */
typedef enum s3eGameCircleLeaderboardFilter {
    /**
     * 
     */
    S3E_GAMECIRCLE_FRIENDS_ALL_TIME = 0,
    /**
     *  
     */
    S3E_GAMECIRCLE_GLOBAL_ALL_TIME = 1,
    /**
     *  
     */
    S3E_GAMECIRCLE_GLOBAL_DAY = 2,
    /**
     *  
     */
    S3E_GAMECIRCLE_GLOBAL_WEEK  = 3,
} s3eGameCircleLeaderboardFilter;

/**
 * ConflictStrategy type
 * 
 */
typedef enum s3eGameCircleConflictStrategy {
    /**
     * 
     */
    S3E_GAMECIRCLE_AUTO_RESOLVE_TO_CLOUD = 1,
    /**
     *  
     */
    S3E_GAMECIRCLE_AUTO_RESOLVE_TO_IGNORE = 2,
    /**
     *  
     */
    S3E_GAMECIRCLE_PLAYER_SELECT = 0,
} s3eGameCircleConflictStrategy;

/**
 * s3eGameCirclePopUpLocation type
 * Various options for placement of the pop up notifications
 */
typedef enum s3eGameCirclePopUpLocation {
    /**
     * 
     */
    S3E_GAMECIRCLE_BOTTOM_CENTER = 0,
    /**
     *  
     */
    S3E_GAMECIRCLE_BOTTOM_LEFT = 1,
    /**
     *  
     */
    S3E_GAMECIRCLE_BOTTOM_RIGHT = 2,
    /**
     *  
     */
    S3E_GAMECIRCLE_TOP_CENTER = 3,
    /**
     *  
     */
    S3E_GAMECIRCLE_TOP_LEFT = 4,
    /**
     *  
     */
    S3E_GAMECIRCLE_OP_RIGHT = 5,
} s3eGameCirclePopUpLocation;


/**
 * s3eGameCircleBlobCallbackStatus type
 * 
 */
typedef enum s3eGameCircleBlobCallbackStatus {
    /**
     * 
     */
    S3E_GAMECIRCLE_BLOB_ALREADYSYNCHRONIZED = 0,
    /**
     *  
     */
    S3E_GAMECIRCLE_BLOB_CONFLICTDEFERRAL = 1,
    /**
     *  
     */
    S3E_GAMECIRCLE_BLOB_GAMEUPLOADSUCCESS = 2,
    /**
     *  
     */
    S3E_GAMECIRCLE_BLOB_SYNCHRONIZEFAILURE = 3,
    /**
     *  
     */
    S3E_GAMECIRCLE_BLOB_NEWGAMEDATA = 4,
} s3eGameCircleBlobCallbackStatus;


/**
 * s3eGameCircleErrorCode type
 * 
 */
typedef enum s3eGameCircleErrorCode {
    /**
     * No error occurred.
     */
    S3E_GAMECIRCLE_NONE = 0,
    /**
     * Indicates an error by the Service that it could not recover from.
     */
    S3E_GAMECIRCLE_UNRECOVERABLE = 1,
    /**
     * Indicates the Amazon Games Service is not bound and ready.
     */
    S3E_GAMECIRCLE_SERVICE_NOT_READY = 2,
    /**
     * Indicates an IOException was thrown while attempting an operation
     */
    S3E_GAMECIRCLE_IO_ERROR = 3,
    /**
     * Indicates a network connection error has occurred, most likely due to losing internet connectivity.
     */
    S3E_GAMECIRCLE_CONNECTION_ERROR = 4,
    /**
     * Indicates the device is not currently authenticated to perform an action. This can be avoided by checking AmazonGames.isAuthenticated()
     */
    S3E_GAMECIRCLE_AUTHENTICATION_ERROR = 5,
    /**
     * General data validation error indicates data provided is not valid
     */
    S3E_GAMECIRCLE_DATA_VALIDATION_ERROR = 6,
} s3eGameCircleErrorCode;

/**
 * This struct is given to S3E_GAMECIRCLE_SYNCHRONIZE_BLOB_CALLBACK callbacks.
 */
typedef struct s3eGameCircleBlobResponse {
    /**
     * Request status.
     */
    s3eGameCircleBlobCallbackStatus m_Status;
    /**
     *
     */
    s3eGameCircleErrorCode m_ErrorCode;
    /**
     */
    void* m_Data;
    
    /**
     *  
     */
    int m_DataLen;
} s3eAmazonBillingItemDataResponse;


typedef enum s3eGameCircleCallback {
    /**
     * Callback for handling responses to s3eGameCircleInitialize.
     * systemData param will be status
     */
    S3E_GAMECIRCLE_INIT_CALLBACK,
    /**
     * Callback for handling responses to s3eGameCircleGetPlayerAlias.
     * In system data pointer will be pointer to alias string. The string are encoded in UTF-8 and kept valid until your callback returns.
     */
    S3E_GAMECIRCLE_PLAYER_ALIAS_CALLBACK,
    /**
     *
     */
    S3E_GAMECIRCLE_SYNCHRONIZE_BLOB_CALLBACK,
    /**
     *
     */
    S3E_GAMECIRCLE_SYNCHRONIZE_BLOB_PROGRESS_CALLBACK,
    /**
     * The number of in-app billing callbacks. Required by S3E.
     */
    S3E_GAMECIRCLE_CALLBACK_MAX
} s3eGameCircleCallback;
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the GameCircle extension is available.
 */
s3eBool s3eGameCircleAvailable();

/**
 * Registers a callback to be called for an operating system event.
 *
 * The available callback types are listed in @ref s3eGameCircleCallback.
 * @param cbid ID of the event for which to register.
 * @param fn callback function.
 * @param userdata Value to pass to the @e userdata parameter of @e NotifyFunc.
 * @return
 *  - @ref S3E_RESULT_SUCCESS if no error occurred.
 *  - @ref S3E_RESULT_ERROR if the operation failed.\n
 *
 * @see s3eGameCircleUnRegister
 * @note For more information on the system data passed as a parameter to the callback
 * registered using this function, see the @ref s3eGameCircleCallback enum.
 */
s3eResult s3eGameCircleRegister(s3eGameCircleCallback cbid, s3eCallback fn, void* userData);

/**
 * Unregister a callback for a given event.
 * @param cbid ID of the callback for which to register.
 * @param fn Callback Function.
 * @return
 * - @ref S3E_RESULT_SUCCESS if no error occurred.
 * - @ref S3E_RESULT_ERROR if the operation failed.\n
 * @note For more information on the systemData passed as a parameter to the callback
 * registered using this function, see the s3eGameCircleCallback enum.
 * @note It is not necessary to define a return value for any registered callback.
 * @see s3eGameCircleRegister
 */
s3eResult s3eGameCircleUnRegister(s3eGameCircleCallback cbid, s3eCallback fn);

/**
 * First method You must call
 * @param bool useAchievements Does game use achievements?
 * @param bool useLeaderboards Does game use leaderboards?
 * @return status
 * 
 */
void s3eGameCircleInitialize(bool useAchievements, bool useLeaderboards);

/**
 * For applications where the AmazonGames client is instantiated well before it is used, this method can ensure that the client is bound and ready for use. 
 * However, it is highly recommended to wait for the S3E_GAMECIRCLE_INIT_CALLBACK callback method to be called instead.
 * @return false until the service is bound and ready to use. Returns true otherwise.
 */
bool s3eGameCircleIsInitialized();

/**
 * 
 * 
 */
void s3eGameCircleShowAchievementsOverlay();

/**
 * Updates progress toward the specified achievement by the specified amount. Result is returned through the returned handle. 
 * The response is a generic RequestResponse If a value outside of range is submitted, it is capped at 100 or 0. If submitted value is less than the stored value, 
 * the update is ignored.
 * 
 */
void s3eGameCircleUpdateAchievement(const char* achievementId, float percentComplete, const char* developerPayload S3E_DEFAULT(NULL));

/**
 * Show the leaderboard overlay for a particular leaderboard.
 */
void s3eGameCircleShowLeaderboardOverlay(const char* leaderboardId);

/**
 * Show the leaderboards overlay for the game.
 */
void s3eGameCircleShowLeaderboardsOverlay();

/**
 * Request that a score be submitted to the leaderboard.
 */
void s3eGameCircleSubmitScore(const char* leaderboardId, int64_t score, const char* developerPayload S3E_DEFAULT(NULL));

S3E_END_C_DECL

/** @} */

#endif /* !S3E_EXT_GAMECIRCLE_H */
